application: hivgsm
version: 10
runtime: python
api_version: 1

handlers:
- url: /_ah/login_required
  script: do_openid_login.py

- url: /static
  static_dir: static

- url: /.*
  script: handler.py
